-- 코드를 작성해주세요
SELECT II.ITEM_ID,II.ITEM_NAME, II.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO II ON IT.ITEM_ID = II.ITEM_ID
JOIN ITEM_INFO PI ON IT.PARENT_ITEM_ID = PI.ITEM_ID
WHERE PI.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;